# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "test golang"

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths:
      - '.github/workflows/tests.yaml'
      - '**.go'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'
          cache: false
      - name: Run tests
        run: go test -v -cover ./...